[global]
   workgroup = NESTLE
   server string = Nestle File Server
   security = user
   map to guest = bad user
   dns proxy = no
   encrypt passwords = yes
   smb encrypt = required
   min protocol = SMB2
   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file
   panic action = /usr/share/samba/panic-action %d

[nestle_shared]
   comment = Recursos Compartidos Nestle
   path = /shared
   browseable = yes
   read only = no
   create mask = 0660
   directory mask = 0770
   valid users = @nestle_users
   force group = nestle_users

[backup]
   comment = Backups del Sistema
   path = /shared/backup
   browseable = yes
   read only = yes
   valid users = nestle_admin
